replicaCount: 1

image:
  repository: ghcr.io/fitrahasfar/devops-microservice/user-service
  tag: 0.0.2
  pullPolicy: Never

service:
  type: ClusterIP
  port: 8000

env:
  DATABASE_URL: postgresql://postgres:postgres@postgres-user:5432/userdb
  REDIS_URL: redis://redis:6379
