apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "order-service.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "order-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "order-service.name" .}}
    spec:
      containers:
        - name: {{ include "order-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "{{ .Values.env.DATABASE_URL }}"
            - name: REDIS_URL
              value: "{{ .Values.env.REDIS_URL }}"
            - name: USER_SERVICE_URL
              value: "{{ .Values.env.USER_SERVICE_URL }}"
